# Generated by Django 3.2.18 on 2023-02-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=64)),
                ('_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
